---
abstract: 'Lightweight TheSchwartz job dispatcher using plain DBI'
author:
  - 'Tatsuhiko Miyagawa <miyagawa@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: TheSchwartz-Simple
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.1
version: 0.01
